# Default values for kube-state-metrics-migration-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: kube-state-metrics-migration
namespace: kube-system


image:
  repository: quay.io/giantswarm/k8s-migrator
  sha: 695c065243382b5be6b0c4dc59c7f58e5b9dd25b

resources:
  limits:
    cpu: 50m
    memory: 75Mi
  requests:
    cpu: 50m
    memory: 75Mi

test:
  image:
    repository: quay.io/giantswarm/alpine-testing
    tag: 0.1.0
