apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: kube-system
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: quay.io/giantswarm/kube-state-metrics:v1.2.0
        args:
        - '--port={{ .Values.port }}'
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.port }}
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.port }}
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 75Mi
          limits:
            cpu: 50m
            memory: 75Mi
      serviceAccountName: {{ .Values.name }}
      hostNetwork: true
