apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        app: {{ .Values.name }}
        giantswarm.io/service-type: "managed"
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - '--port={{ .Values.port }}'
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.port }}
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.port }}
          initialDelaySeconds: 5
          timeoutSeconds: 5
      - name: addon-resizer
        image: "{{ .Values.imageResizer.registry }}/{{ .Values.imageResizer.repository }}:{{ .Values.imageResizer.tag }}"
        resources:
          limits:
            cpu: 150m
            memory: 50Mi
          requests:
            cpu: 150m
            memory: 50Mi
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command:
          - /pod_nanny
          - --container={{ .Values.name }}
          - --cpu=200m
          - --extra-cpu=1m
          - --memory=300Mi
          - --extra-memory=5Mi
          - --threshold=5
          - --deployment={{ .Values.name }}
      serviceAccountName: {{ .Values.name }}
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
