apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: kube-system
  labels:
    app: kube-state-metrics
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/scheme: "http"
spec:
  ports:
  - port: 10301
  selector:
    app: kube-state-metrics
