apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: kube-system
  labels:
    app: {{ .Values.name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
spec:
  ports:
  - port: 10301
  selector:
    app: {{ .Values.name }}
